export interface Cars{
    _id: string,
    imageUrl: string,
	Year: number,
    Make: string,
    Model: string,
    UsedNew: string,
    Price: string,
    ConsumerRating: number,
    ConsumerReviews: number,
    SellerType: string,
    SellerName: string,
    SellerRating: number,
    SellerReviews:number,
    StreetName: string,
    State: string,
    Zipcode: string,
    DealType: string,
    ComfortRating: number,
    InteriorDesignRating: number,
    PerformanceRating: number,
    ValueForMoneyRating: number,
    ExteriorStylingRating: number,
    ReliabilityRating: number,
    ExteriorColor: string,
    InteriorColor: string,
    Drivetrain: string,
    MinMPG: number,
    MaxMPG: number,
    FuelType: string,
    Transmission: string,
    Engine: string,
    VIN: string,
    Stock: string, 
    Mileage: number,
}
export interface Companies{
    name: string,
    imageUrl: string,
    description: string
}